# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

WORKDIR /app

# Copy package files
COPY package.json package-lock.json ./

# Install dependencies (ignore scripts and build from typescript manually)
RUN npm install --ignore-scripts

# Copy the rest of the source code
COPY . .

# Build the typescript code
RUN npm run build

# Expose port if needed (not necessary for stdio server)

# Run the MCP server
CMD [ "node", "build/index.js" ]
